<link href="${basePath}/static/css/default-style.css" rel="stylesheet" type="text/css"/>
<link href="${basePath}/static/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css"/>
<link href="${basePath}/static/sweetalert/sweetalert.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="${basePath}/static/js/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="${basePath}/static/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="${basePath}/static/sweetalert/sweetalert.min.js"></script>
<script type="text/javascript" src="${basePath}/static/js/Utils.js"></script>
<script type="text/javascript" src="${basePath}/static/js/menu/menu.js"></script>
<script type="text/javascript" src="${basePath}/static/js/top/top.js"></script>